export const resource = [
    {
      'id': '1',
      'active': true,
      'name': 'GPT',
      'description': 'GPT сеть',
      'chapter': 'Чаты',
      'external': true,
      'popular': false,
      'newTile': false,
      'dateEdit': 1741636795,
      'createdAt': 1741636795,
      'image': 'https://loremflickr.com/640/480/animals',
      'settings': {}
    },
    {
      'id': '2',
      'active': false,
      'name': 'Midjourney ',
      'description': 'Генерирует изображения. Сеть Midjourney  5.2 / 6 ',
      'chapter': 'Изображения',
      'external': true,
      'popular': false,
      'newTile': false,
      'dateEdit': 1741636735,
      'createdAt': 1741636735,
      'image': 'https://loremflickr.com/640/480/business',
      'settings': {}
    },
    {
      'id': '3',
      'active': true,
      'name': 'YaGPT',
      'description': 'Отвечает на вопросы. Сеть YaGPT Яндекс',
      'chapter': 'Чаты',
      'external': true,
      'popular': false,
      'newTile': false,
      'dateEdit': 1741636675,
      'createdAt': 1741636675,
      'image': 'https://loremflickr.com/640/480/city',
      'settings': {}
    },
    {
      'id': '4',
      'active': true,
      'name': 'YaArt',
      'description': 'Генерирует изображения. Сеть YaGPT Яндекс',
      'chapter': 'Изображения',
      'external': true,
      'popular': false,
      'newTile': true,
      'dateEdit': 1741636615,
      'createdAt': 1741636615,
      'image': 'https://loremflickr.com/640/480/technics',
      'settings': {}
    },
    {
      'id': '5',
      'active': true,
      'name': 'Переводчик',
      'description': "Переводит текст на любой язык. Сеть NLLB-200 развернута в ПАО 'Ростелеком'",
      'chapter': 'Тестирование',
      'external': false,
      'popular': false,
      'newTile': false,
      'dateEdit': 1741636555,
      'createdAt': 1741636555,
      'image': 'https://loremflickr.com/640/480/food',
      'settings': {}
    },
    {
      'id': '6',
      'active': true,
      'name': 'Deepl',
      'description': 'Переводит текст на любой язык. Сеть Deepl',
      'chapter': 'Перевод',
      'external': false,
      'popular': true,
      'newTile': true,
      'dateEdit': 1741636495,
      'createdAt': 1741636495,
      'image': 'https://loremflickr.com/640/480/nature',
      'settings': {}
    }
];
